#!/usr/bin/env python3
"""
Generate a one-off SQL import script for the current `courses` table schema.

The crawler JSON contains more fields than the backend currently stores, so this
script keeps only the fields the application actually uses today:
  - name
  - professor
  - department
  - category
  - type
  - credits
  - section
  - semester
  - rating (default 0)
  - review_count (default 0)

It also deduplicates rows over that mapped shape.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


@dataclass(frozen=True)
class CourseRow:
    name: str
    professor: str
    department: str
    category: str
    type: str
    credits: int
    section: str
    semester: str
    rating: float = 0.0
    review_count: int = 0


def normalize_department(raw: str) -> str:
    raw = (raw or "").strip()
    if " / " in raw:
        return raw.split(" / ", 1)[0].strip()
    return raw


def normalize_category(raw_type: str) -> str:
    raw_type = (raw_type or "").strip()
    return "전공" if raw_type.startswith("전공") else "교양"


def normalize_credits(raw_credit: str) -> int:
    raw_credit = (raw_credit or "0").strip()
    return int(float(raw_credit))


def normalize_section(raw_id: str) -> str:
    raw_id = (raw_id or "").strip()
    if "-" not in raw_id:
        return "001"
    suffix = raw_id.rsplit("-", 1)[-1].strip()
    return suffix or "001"


def map_row(item: dict, semester: str) -> CourseRow:
    return CourseRow(
        name=(item.get("name") or "").strip(),
        professor=(item.get("professor") or "").strip(),
        department=normalize_department(item.get("dept") or ""),
        category=normalize_category(item.get("type") or ""),
        type=(item.get("type") or "").strip(),
        credits=normalize_credits(item.get("credit") or "0"),
        section=normalize_section(item.get("id") or ""),
        semester=semester,
    )


def dedupe_rows(rows: Iterable[CourseRow]) -> list[CourseRow]:
    seen: set[CourseRow] = set()
    deduped: list[CourseRow] = []
    for row in rows:
        if not row.name or not row.professor or not row.department:
            continue
        if row in seen:
            continue
        seen.add(row)
        deduped.append(row)
    return deduped


def sql_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "''")


def row_to_sql_tuple(row: CourseRow) -> str:
    return (
        f"('{sql_escape(row.name)}', "
        f"'{sql_escape(row.professor)}', "
        f"'{sql_escape(row.department)}', "
        f"'{sql_escape(row.category)}', "
        f"'{sql_escape(row.type)}', "
        f"{row.credits}, "
        f"'{sql_escape(row.section)}', "
        f"'{sql_escape(row.semester)}', "
        f"{row.rating:.1f}, "
        f"{row.review_count})"
    )


def build_sql(rows: list[CourseRow], source_path: Path, semester: str) -> str:
    lines = [
        "-- Generated by backend/scripts/generate_course_import_sql.py",
        f"-- Source: {source_path}",
        f"-- Semester: {semester}",
        f"-- Row count after dedupe: {len(rows)}",
        "SET NAMES utf8mb4;",
        "START TRANSACTION;",
        "DELETE FROM courses;",
        "ALTER TABLE courses AUTO_INCREMENT = 1;",
    ]

    batch_size = 500
    for start in range(0, len(rows), batch_size):
        batch = rows[start : start + batch_size]
        values = ",\n  ".join(row_to_sql_tuple(row) for row in batch)
        lines.append(
            "INSERT INTO courses "
            "(name, professor, department, category, type, credits, section, semester, rating, review_count)\n"
            "VALUES\n"
            f"  {values};"
        )

    lines.extend(["COMMIT;", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate SQL to import crawler course JSON into the current courses table."
    )
    parser.add_argument(
        "--source",
        default="crawler/data/courses.json",
        help="Path to crawler JSON file (default: crawler/data/courses.json)",
    )
    parser.add_argument(
        "--semester",
        required=True,
        help='Semester label to store in DB, e.g. "26-1"',
    )
    parser.add_argument(
        "--output",
        default="backend/sql/import_courses.sql",
        help="Output SQL path (default: backend/sql/import_courses.sql)",
    )
    args = parser.parse_args()

    source_path = Path(args.source)
    output_path = Path(args.output)

    with source_path.open(encoding="utf-8") as f:
        raw_data = json.load(f)

    mapped_rows = [map_row(item, args.semester) for item in raw_data]
    rows = dedupe_rows(mapped_rows)
    sql = build_sql(rows, source_path, args.semester)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(sql, encoding="utf-8")

    print(f"Generated SQL: {output_path}")
    print(f"Input rows: {len(raw_data)}")
    print(f"Imported rows after dedupe: {len(rows)}")


if __name__ == "__main__":
    main()
